# Generated by Django 2.1.1 on 2018-10-10 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=30, verbose_name='Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Category_sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=30, verbose_name='Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=10, verbose_name='Stock exchange')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('ipoYear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='IPO Year')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Key in date')),
                ('category_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Category_sector', verbose_name='Sector')),
                ('category_excess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Category_industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Stock data',
                'ordering': ['symbol'],
            },
        ),
    ]
