# Generated by Django 2.1.1 on 2018-10-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date'], 'verbose_name': 'Stock data'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category_excess',
            new_name='category_industry',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category_cover',
            new_name='category_sector',
        ),
    ]
