# Generated by Django 2.1.1 on 2018-10-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_stock_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_daily',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualization.Stock', verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
