# Generated by Django 2.1.1 on 2018-10-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_stock_daily_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_daily',
            name='stock',
        ),
    ]
