# Generated by Django 2.1.1 on 2018-10-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_remove_stock_daily_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_daily',
            options={'ordering': ['date'], 'verbose_name': 'Stock daily'},
        ),
    ]
