# Generated by Django 2.1.1 on 2018-10-13 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_auto_20181011_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_intraday_1min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('open', models.FloatField(verbose_name='Open price')),
                ('high', models.FloatField(verbose_name='High price')),
                ('low', models.FloatField(verbose_name='Low price')),
                ('close', models.FloatField(verbose_name='Close price')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Key in date')),
            ],
            options={
                'verbose_name': 'Stock intra day 1 min',
                'ordering': ['date'],
            },
        ),
    ]
